### ISSUE TITLE
Failed at the vue-jwt-auth-example@1.0.0 dev script 'webpack-dev-server --inline --hot'

### ISSUE THREAD

**Issue by Sbudah** [auth0/vue-jwt-authentication#10]
Please advise what I am doing wrong here. The script will not run because of the error above.

**Comment by chenkie** [comment]
Are you sure you have everything installed from npm? I just tried and didn't get any errors.

**Comment by Sbudah** [comment]
I just tried re-installing and I got the following

`npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path ../mime/cli.js
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../mime/cli.js' -> '/var/www/vue-jwt-authentication/server/node_modules/.bin/mime'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6`

I can try npm install --no-bin-links but I suspect that that's what causes the webpack error.

Oh, one more thing...

`vagrant@scotchbox:/var/www/vue-jwt-authentication/server$ npm install
npm WARN deprecated jsonwebtoken@1.1.2: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
npm WARN deprecated jws@0.2.6: Security update: Versions below 3.0.0 are deprecated.`

**Comment by chenkie** [comment]
Gotcha. So it's a Vagrant + webpack issue then.

I saw this comment from another issue which might help:

```
Just another thing to watch out for: Make sure Virtualbox Extension Pack 
is installed (some people miss this and it produces the same 
symlink error outlined above)
```

**Comment by Sbudah** [comment]
Thanks for the help.

I installed webpack and webpack-dev-server globally and that seems to allow the project to be built.

I will keep on fiddling with it until I figure out some minor items.

**Comment by chenkie** [comment]
👍
