### ISSUE TITLE
Why there are duplicate api calls?

### ISSUE THREAD

**Issue by xueenda** [auth0/vue-jwt-authentication#6]
I noticed for every api call there is a method "options" call first and then is the real api call.
Why is that?
How can I just make one "get" or "post" call?

random-quote    OPTIONS 204 xhr build.js:15 258 B 5 ms  
random-quote    GET 200 xhr Other   292 B 5 ms  
users/  OPTIONS 204 xhr build.js:15 272 B 5 ms  
users/  POST    201 xhr Other   423 B 39 ms 
create/ OPTIONS 204 xhr build.js:15 272 B 4 ms  
create/ POST    201 xhr Other   423 B 9 ms

**Comment by GeorgeYan** [comment]
Hey ~ I have a twice http request too,  how to fix?

**Comment by xueenda** [comment]
You don't have to fix. That's the behaviour of cross origin http request.

**Comment by GeorgeYan** [comment]
@xueenda Got it , Thanks for you reply~ :D

**Comment by rcadhikari** [comment]
When performing certain types of cross-domain Ajax requests, modern browsers that support CORS will insert an extra "preflight" request to determine whether they have permission to perform the action ([reference](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing))
